package com.zhangpeng.videowebsite.javabean;

public class FavouriteList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favouritelist.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favouritelist.vid
     *
     * @mbg.generated
     */
    private Integer vid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favouritelist.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favouritelist.id
     *
     * @return the value of favouritelist.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favouritelist.id
     *
     * @param id the value for favouritelist.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favouritelist.vid
     *
     * @return the value of favouritelist.vid
     *
     * @mbg.generated
     */
    public Integer getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favouritelist.vid
     *
     * @param vid the value for favouritelist.vid
     *
     * @mbg.generated
     */
    public void setVid(Integer vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favouritelist.uid
     *
     * @return the value of favouritelist.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favouritelist.uid
     *
     * @param uid the value for favouritelist.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}