<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>视频分类</title>
<link href="../css/app.css?985bcb14808bc6c67072" rel="stylesheet"></head>
<body>
    <!-- 文件分类列表展示 -->
<script type="text/javascript" src="../js/app.js?985bcb14808bc6c67072"></script></body>
</html>