<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>后台管理</title>
    <link href="../css/app.css?985bcb14808bc6c67072" rel="stylesheet">
</head>
<body>
<!--内容管理 -->
<!-- 首页轮播图的增删查改 -->
<!-- 用户管理 -->
<!-- 权限管理 -->
<script type="text/javascript" src="../js/app.js?985bcb14808bc6c67072"></script>
<script type="text/javascript" src="../js/jqthumb.min.js"></script>
</body>
</html>